[package]
name = "lox"
version = "0.1.0"
authors = ["Kevin Garner <kevin@kgar.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "~2.27.0"
